# Generated by Django 5.0.3 on 2024-04-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='music',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
