# Generated by Django 5.0.3 on 2024-04-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0003_songs_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='movie_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
